### ISSUE TITLE
Demo Site is facing errors

### ISSUE THREAD

**Issue by parasparmar** [simplcommerce/SimplCommerce#949]
Hi Team

Just wanted to say that your demo site https://demo.simplcommerce.com/ and https://demo.simplcommerce.com/login?ReturnUrl=%2Fadmin is not working correctly.

![p1f6BAjtGn](https://user-images.githubusercontent.com/2953468/97142255-50960e80-1786-11eb-8f64-847518f376cd.png)

**Comment by thiennn** [comment]
Thanks! The issue has been fixed

**Comment by parasparmar** [comment]
Sorry, brother. The demo site is still not working.
Here's the screenshot.

Ps. Please excuse any typos. This is being sent from my phone.

Paras Parmar 7738533134
